# -*- coding: utf-8 -*-
"""동아리 프로젝트(이상치 탐지).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13vHx3w4i9qCYCSsDle8D4JCzMms6Ro5i
"""

import streamlit as st
import requests
from bs4 import BeautifulSoup
from google import genai
import plotly.graph_objects as go
import re
import gspread
from google.oauth2.service_account import Credentials
import json

# --- 1. 페이지 설정 및 디자인 ---
st.set_page_config(page_title="AI 물가 파수꾼", layout="wide")
st.title("🛡️ AI 기반 물가 조기 경보 및 자가 검증 시스템")
st.markdown("뉴스 빅데이터 분석을 통해 물가 상승 요인을 선제적으로 감지하고 예측 적중도를 평가합니다.")

# --- 2. 사이드바 설정 ---
st.sidebar.header("⚙️ 설정 및 보안")
api_key = st.sidebar.text_input("🔑 Gemini API 키를 입력하세요", type="password")
st.sidebar.info("API 키는 세션 종료 시 저장되지 않으므로 안심하세요.")

# --- 3. 메인 기능 탭 구성 ---
tab1, tab2, tab3 = st.tabs(["🔍 실시간 분석", "📈 위험도 대시보드", "✅ 예측 적중도 검증"])

# 뉴스 수집 공통 함수
def get_news():
    urls = {"경제": "101", "국제": "104", "IT": "105"}
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}
    news_data = []
    try:
        for cat, code in urls.items():
            res = requests.get(f"https://news.naver.com/section/{code}", headers=headers, timeout=5)
            soup = BeautifulSoup(res.text, "html.parser")
            titles = soup.select(".sa_text_strong")
            for t in titles[:8]:
                news_data.append(f"[{cat}] {t.text.strip()}")
        return news_data
    except Exception as e:
        return [f"뉴스 수집 중 오류 발생: {e}"]

# --- Tab 1: 실시간 분석 ---
with tab1:
    if st.button("🚀 뉴스 수집 및 분석 시작"):
        if not api_key:
            st.warning("왼쪽 사이드바에 API 키를 먼저 입력해주세요!")
        else:
            with st.spinner("최신 뉴스를 샅샅이 수집하고 분석 중입니다..."):
                news_list = get_news()
                st.session_state['news_list'] = news_list

                try: # 💡 안정성을 위한 예외 처리(try-except) 추가
                    client = genai.Client(api_key=api_key)
                    prompt = f"""
                    너는 거시경제 애널리스트야. 아래 뉴스들을 보고 다음을 수행해:
                    1. 전체 물가 상승 위험도 점수 (반드시 답변 맨 처음에 '점수: 85'처럼 숫자만 명확히 적을 것)
                    2. 가격 급등 예상 품목 Top 3 (인과관계 중심으로 설명)
                    3. 원인 파악 (담합, 전쟁, 기상이변 등 구체적 언급)
                    뉴스 데이터: {news_list}
                    """
                    response = client.models.generate_content(model='gemini-2.5-flash', contents=prompt)
                    st.session_state['full_report'] = response.text

                    # 💡 정규표현식을 이용한 똑똑한 숫자 추출
                    try:
                        # 텍스트 안에서 연속된 숫자(점수)를 찾음
                        numbers = re.findall(r'\d+', response.text)
                        if numbers:
                            # 첫 번째로 찾은 숫자를 점수로 사용하되, 100을 넘지 않도록 설정
                            score = min(int(numbers[0]), 100)
                        else:
                            score = 50 # 숫자를 못 찾으면 기본값 50
                        st.session_state['risk_score'] = score
                    except:
                        st.session_state['risk_score'] = 50

                    st.success("✅ 분석이 완료되었습니다! '위험도 대시보드' 탭을 확인하세요.")
                    st.write(response.text)

                except Exception as e:
                    # API 키가 틀렸거나 구글 서버에 문제가 있을 때 웹사이트가 멈추지 않도록 함
                    st.error(f"❌ AI 분석 중 문제가 발생했습니다. API 키가 정확한지 확인해주세요! (에러 상세: {e})")

# --- Tab 2: 위험도 대시보드 ---
with tab2:
    if 'risk_score' in st.session_state:
        st.subheader("📊 오늘의 물가 상승 위험 지수")

        # 게이지 차트 시각화
        fig = go.Figure(go.Indicator(
            mode = "gauge+number",
            value = st.session_state['risk_score'],
            domain = {'x': [0, 1], 'y': [0, 1]},
            title = {'text': "물가 위험도", 'font': {'size': 24}},
            gauge = {
                'axis': {'range': [None, 100], 'tickwidth': 1},
                'bar': {'color': "darkblue"},
                'steps' : [
                    {'range': [0, 30], 'color': "lightgreen"},
                    {'range': [30, 70], 'color': "yellow"},
                    {'range': [70, 100], 'color': "red"}]}))
        st.plotly_chart(fig)

        with st.expander("📝 분석 근거(수집된 원본 뉴스) 확인하기"):
            for n in st.session_state['news_list']:
                st.write(n)
    else:
        st.info("먼저 '실시간 분석' 탭에서 [🚀 분석 시작] 버튼을 눌러주세요.")

# --- Tab 3: 예측 적중도 검증 ---
with tab3:
    st.subheader("🎯 Self-Feedback: 과거 예측 검증")
    st.markdown("과거 AI가 경고했던 물가 위험 품목이 오늘 실제 기사화되었는지 대조하여 스스로 채점합니다.")

    if 'full_report' in st.session_state:
        if st.button("🕵️ 현재 뉴스에서 적중 사례 찾기"):
            with st.spinner("오늘 뜬 뉴스에서 과거 예측 내용이 언급되었는지 매칭 중..."):
                try:
                    current_news = get_news()
                    client = genai.Client(api_key=api_key)
                    check_prompt = f"""
                    [과거의 AI 예측 보고서]: {st.session_state['full_report']}
                    [오늘 수집된 최신 뉴스]: {current_news}

                    네가 과거에 예측했던 물가 상승 요인이나 위험 품목이 '오늘 최신 뉴스'에서 실제로 기사화되었는지 대조해봐.
                    맞았다면 '✅ 적중!', 아직 징후가 없다면 '⏳ 진행중'으로 나누어서 결과를 요약해줘.
                    """
                    check_res = client.models.generate_content(model='gemini-2.5-flash', contents=check_prompt)
                    st.success("대조가 완료되었습니다!")
                    st.write(check_res.text)
                except Exception as e:
                    st.error(f"검증 중 오류가 발생했습니다: {e}")
    else:
        st.info("저장된 과거 예측 데이터가 없습니다. 분석을 먼저 실행해 주세요.")
